### ISSUE TITLE
首页的轮转图优化

### ISSUE THREAD

**Issue by cctv1005s** [10Web/static#9]
![image](https://user-images.githubusercontent.com/16508727/55452108-adf8c680-5608-11e9-8f58-7e904d7a0427.png)

首页的轮转图还是感觉不够自然

**Comment by ghost** [comment]
轮转图问题已修复，请学长验收
2019.04.15 10：54

**Comment by cctv1005s** [comment]
closed
https://github.com/10Web/static/pull/11
